steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/massive-network-379402/ml-prediction/mlmodel:latest', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/massive-network-379402/ml-prediction/mlmodel:latest']
options:
  logging: CLOUD_LOGGING_ONLY